modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="guns_and_weapons_plus"
version="1.0.0"
displayName="Guns And Weapons Plus"
credits="https://discord.gg/NAqZFCfxYB"
displayURL="https://discord.gg/NAqZFCfxYB"
updateJSONURL="https://discord.gg/NAqZFCfxYB"
authors="The_WereF0X"
description="Extension for the mod Guns and Weapons"

[[dependencies.guns_and_weapons_plus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.guns_and_weapons_plus]]
    modId="gun_mod"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.guns_and_weapons_plus]]
    modId="gun_mod"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.guns_and_weapons_plus]]
    modId="gun_mod"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
